version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nocturnal_nginx
    ports:
      - "8005:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: nocturnal_php
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/app?serverVersion=15&charset=utf8

  db:
    image: postgres:15-alpine
    container_name: nocturnal_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  node:
    image: node:20-alpine
    container_name: nocturnal_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5175:5173"

volumes:
  db_data:
